SOURCES     = george.cpp ringo.cpp georgeringo.cpp
OUTPUTFILE  = lib_readme.txt
INSTALLDIR  = /usr/include

compile:
install: FORCE
	mkdir -p $(INSTALLDIR)
    	cp -p $(OUTPUTFILE) $(INSTALLDIR)/$(OUTPUTFILE)
FORCE: