#ifndef PICPUMONITORING_GLOBAL_H
#define PICPUMONITORING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PICPUMONITORING_LIBRARY)
#  define PICPUMONITORINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PICPUMONITORINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PICPUMONITORING_GLOBAL_H
